---
name: Label Checker
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled

jobs:
  check_labels:
    name: Check labels
    runs-on: ubuntu-latest
    steps:
      - uses: LogicSoftware/label-checker@main
        with:
          any_of: tested,partial
          github-token: ${{ secrets.GITHUB_TOKEN }}
  submit_result:
    name: Check labels
    runs-on: ubuntu-latest
    if: ${{ env.labels_check_passed }}
    steps:
      - uses: actions/github-script@v3
        with:
          script: |
            // do nothing
