---
name: Label Checker
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled
      - edited

permissions: write-all

jobs:
  check_labels:
    name: Check labels
    runs-on: ubuntu-latest
    steps:
      - uses: LogicSoftware/label-checker@review_variant
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
